### ISSUE TITLE
Crypto is very weak

### ISSUE THREAD

**Issue by tbodt** [mderazon/node-fpe#1]
This is just a substitution cipher.

**Comment by mderazon** [comment]
I tried to implement a `prefix-cipher` as described here:
https://en.wikipedia.org/wiki/Format-preserving_encryption#FPE_from_a_prefix_cipher

Do you see anything wrong with the implementation ?

**Comment by tbodt** [comment]
Yeah, you're running FPE on each digit individually, rather than the whole message. The domain is supposed to be the set of every possible message, not the set of digits. This is why this algorithm is infeasible for more than very small messages.

**Comment by mderazon** [comment]
You're right. Thanks for pointing it out.
After reading [here](http://ourdigitalmags.com/publication/?i=301400&article_id=2476983) I realize this technique might not be very suitable if you need large domains.

One option would be to fix it and allow the user choose the character set (for example digits) and the domain size (for example, a 9 digit number), create all the permutations possible and encrypt them all, sort, and create the permutations. This might take a lot of bootstrap time for large domains.

Other option would be to use the cycle walking technique, should be easy to implement, however the runtime is not deterministic.

**Comment by tbodt** [comment]
The domain of 9 digit numbers would take multiple gigabytes to store and would probably take hours to compute. I'd say it's best to use cycle walking with a permutation based on a feistel structure, that way the size of the permutation can be within a factor of 2 of the size of the domain and cycle walking will finish quickly.

**Comment by mderazon** [comment]
Reading through https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-38G.pdf

Need more time to learn to implement ff1/ff3. Looks like there are couple of implementations in [Go](https://github.com/cloudtrust/fpe) and C I might be able to learn from.
